* Second take on my website

** Goals

- Aesthetics that align with me
- Accessibility
- Compliance to simple standards
- Greek/English and light/dark mode switching
- Instant access to the text on load
- Text that stays in place as data loads

** Aesthetics

Oftentimes, there's a mismatch between
the appearance of someone's website
and the appearance of their house, car and workspace.
The website tends to have an energetic aesthetic.
This website is meant to be mine in every sense.

** Tools

None. This is an improvised workflow, inspired by LaTeX
and general experiences programming.

** Upgrade

The first version of my website used PHP functions to
concatenate strings into HTML.
Near the end, the localization was handled using custom XML files.

This version used to be served almost as-is,
with custom 'def-macro' DOM elements expanding using JavaScript,
and span elements with both languages such that half would be
hidden. However Emacs' 'EWW' can't client side render.

Currently, there's simple XML that names chunks of text
both in Greek and in English, and there's PHP that
places the chunks of text inside of DOM elements.
This is as close to raw HTML as possible,
while avoiding most duplicate code.

Also the latest updates as of updating this README
replaced the menu at the top with plain text that has links.
That reduces the code massively, especially because
it's trivial to make it accessible and support mobile view.

** Message

This kind of website is trivial to improvise,
I improvised 3 versions in a few months.
If it doesn't work out, there's not a lot to rework.
Keep in mind that parsing simple XML is a trivial task,
so you may come up with some simple XML format
that allows you to easily switch frameworks late.

The benefit of loading the complexity on the mind,
and offloading it from the computer,
is that when the computer doesn't feel well it doesn't go unnoticed.
